trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    apt update
    npm install
  displayName: 'npm install'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'main.js'
    artifactName: main.js
  displayName: 'Publish npm artifact'
