version: 0.2 


phases:
  install:
     runtime-versions:
       nodejs: 16
    
  build:
    commands:
      - npm install
      - npm install pm2 -g
      
artifacts:
  files:
    - main.js
    - ecosystem.json
    - package.json
    - appspec.yml
