version: 0.2 


phases:
  - install:
      runtime-versions:
        nodejs: 10
        
  - pre_build: 
      - commands:
          - npm install  
  -build:
     - commands:
         - npm run

artifacts:
  - files:
      - main.js
      - ecosystem.json
      - package.json
      - appspec.yml
