version: 0.2 


phases:
  install:
      runtime-versions:
        nodejs: 16
   
  build:
    commands:
      - npm install
      
  post_build:
    commands:
      - npm i
      - npm start

artifacts:
  files:
    - main.js
    - ecosystem.json
    - package.json
    - appspec.yml
